### ISSUE TITLE
Sau 50p bot không chạy :)

### ISSUE THREAD

**Issue by NOTAD** [lequanglam/c3c#8]
[2020-04-06T21-46-37.773Z] [Facebook] Destroying Facebook Chat instance and creating a new one... (50 minutes clock)
[2020-04-06T21-46-37.773Z] [INTERNAL] Detected process is shutting down, handling...
[2020-04-06T21-46-37.791Z] [Facebook] Stopped Facebook listener

[2020-04-06T21-46-37.794Z] [INTERNAL] Stopped auto-save.
[2020-04-06T21-46-37.797Z] [INTERNAL] Unloaded plugin ArrowChat
1.0 by UIRI
[2020-04-06T21-46-37.800Z] [INTERNAL] Unloaded plugin Broadcast
1.3 by UIRI
[2020-04-06T21-46-37.803Z] [INTERNAL] Unloaded plugin COVID-19 Updater 1.0 by UIRI
[2020-04-06T21-46-37.806Z] [INTERNAL] Unloaded plugin DenyCommand 1.0 by UIRI
[2020-04-06T21-46-37.809Z] [INTERNAL] Unloaded plugin DisableBot 1.0 by UIRI
[2020-04-06T21-46-37.811Z] [INTERNAL] Unloaded plugin Economy-Gambling 0.6 by UIRI
[2020-04-06T21-46-37.814Z] [INTERNAL] Unloaded plugin Economy-Income 0.3 by UIRI
[2020-04-06T21-46-37.818Z] [INTERNAL] Unloaded plugin Economy-Rain 1.1 by UIRI
[2020-04-06T21-46-37.821Z] [INTERNAL] Unloaded plugin Economy 0.6 by UIRI
[2020-04-06T21-46-37.824Z] [INTERNAL] Unloaded plugin eXPerienceChat 1.2 by UIRI
[2020-04-06T21-46-37.827Z] [INTERNAL] Unloaded plugin Giftcode 1.1 by UIRI
[2020-04-06T21-46-37.830Z] [INTERNAL] Unloaded plugin LibBetterRandom  by UIRI, Sean McCullough, Takuji Nishimura and Makoto Matsumoto
[2020-04-06T21-46-37.833Z] [INTERNAL] Unloaded plugin MathSolve
0.3 by UIRI
[2020-04-06T21-46-37.836Z] [INTERNAL] Unloaded plugin MP3Voice 2.0.1NB by UIRI
[2020-04-06T21-46-37.838Z] [INTERNAL] Unloaded plugin Ping 1.0.0 by UIRI
[2020-04-06T21-46-37.841Z] [INTERNAL] Unloaded plugin SimSimi 1.4 Non-block by UIRI
[2020-04-06T21-46-37.846Z] [INTERNAL] Unloaded plugin Text-To-Speech 1.0.1 by UIRI
[2020-04-06T21-46-37.848Z] [INTERNAL] Unloaded plugin Weather 1.1 by XxBoomer, rev. UIRI
[2020-04-06T21-46-37.953Z] [INTERNAL] Saved data.
[2020-04-06T21-46-37.957Z] [INTERNAL] Closed local HTTP Model Server.
[2020-04-06T21-46-37.960Z] [INTERNAL] Closing bot with code 1...

console@c3c:js#
C:\Users\Administrator\Desktop\c3ccc\node_modules\fca-unofficial\index.js:347
    appState.map(function(c) {
             ^

TypeError: appState.map is not a function
    at loginHelper (C:\Users\Administrator\Desktop\c3ccc\node_modules\←[4mfca-unofficial←[24m\index.js:347:14)
    at login (C:\Users\Administrator\Desktop\c3ccc\node_modules\←[4mfca-unofficial←[24m\index.js:567:3)
    at Timeout.forceReconnect [as _onTimeout] (C:\Users\Administrator\Desktop\c3ccc\main.js:2834:46)
←[90m    at listOnTimeout (internal/timers.js:549:17)←[39m
←[90m    at processTimers (internal/timers.js:492:7)←[39m

[Loader] main.js throw 1 (not 7378278/RESTART). Shutting down...

**Comment by lequanglam** [comment]
đã fix
